name: Build demo

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        idf_ver: ["release-v5.0"]
        idf_target: ["esp32s3"]
    runs-on: ubuntu-20.04
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build demo
        env:
          IDF_TARGET: ${{ matrix.idf_target }}
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          idf.py set-target ${{matrix.idf_target}} build
          cd build
          TARGET_CHIP=`cat project_description.json | python3 -c 'import sys,json; print(json.load(sys.stdin)["target"])'`
          APP_BIN=`cat project_description.json | python3 -c 'import sys,json; print(json.load(sys.stdin)["app_bin"])'`
          esptool.py --chip $IDF_TARGET merge_bin -o "multiple_lcd_$IDF_TARGET.bin" `cat flash_args | tr '\n' '\ '`
      - name: Update release
        uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            build/multiple_lcd_${{ matrix.idf_target }}.bin
          tag: multiple_lcd_latest